# Generated by Django 4.2.8 on 2023-12-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0002_trivia_triviaquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='triviaquestion',
            name='correct_answered',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
