# Generated by Django 4.2.10 on 2024-02-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0003_triviaquestion_correct_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='trivia',
            name='name',
            field=models.CharField(default='Trivia', max_length=512),
            preserve_default=False,
        ),
    ]
